<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="theme-color" content="#222"><meta name="generator" content="Hexo 6.3.0">

  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png">
  <link rel="mask-icon" href="/images/logo.svg" color="#222">

<link rel="stylesheet" href="/css/main.css">



<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha256-Z1K5uhUaJXA7Ll0XrZ/0JhX4lAtZFpT6jkKrEDT0drU=" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" integrity="sha256-PR7ttpcvz8qrF57fur/yAx1qXMFJeJFiA6pSzWi0OIE=" crossorigin="anonymous">

<script class="next-config" data-name="main" type="application/json">{"hostname":"stefanomattia.github.io","root":"/","images":"/images","scheme":"Muse","darkmode":false,"version":"8.14.0","exturl":false,"sidebar":{"position":"left","display":"hide","padding":18,"offset":12},"copycode":{"enable":false,"style":null},"bookmark":{"enable":false,"color":"#222","save":"auto"},"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"stickytabs":false,"motion":{"enable":true,"async":false,"transition":{"menu_item":"fadeInDown","post_block":"fadeIn","post_header":"fadeInDown","post_body":"fadeInDown","coll_header":"fadeInLeft","sidebar":"fadeInUp"}},"prism":false,"i18n":{"placeholder":"Searching...","empty":"We didn't find any results for the search: ${query}","hits_time":"${hits} results found in ${time} ms","hits":"${hits} results found"}}</script><script src="/js/config.js"></script>

    <meta name="description" content="I recently started to look into the R language, as part of my growing interest in statistical learning and data analysis. As a first impression, I felt a bit overwhelmed by the number of differences w">
<meta property="og:type" content="article">
<meta property="og:title" content="Plotting Sentinel-5P NetCDF products with R and ggplot2">
<meta property="og:url" content="http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/index.html">
<meta property="og:site_name" content="Space to Ground">
<meta property="og:description" content="I recently started to look into the R language, as part of my growing interest in statistical learning and data analysis. As a first impression, I felt a bit overwhelmed by the number of differences w">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/unnamed-chunk-13-1.png">
<meta property="og:image" content="http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/unnamed-chunk-14-1.png">
<meta property="article:published_time" content="2018-02-14T13:31:33.000Z">
<meta property="article:modified_time" content="2018-03-02T13:33:02.000Z">
<meta property="article:author" content="Stefano Mattia">
<meta property="article:tag" content="rstats">
<meta property="article:tag" content="ggplot2">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/unnamed-chunk-13-1.png">


<link rel="canonical" href="http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/">



<script class="next-config" data-name="page" type="application/json">{"sidebar":"","isHome":false,"isPost":true,"lang":"en","comments":true,"permalink":"http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/","path":"2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/","title":"Plotting Sentinel-5P NetCDF products with R and ggplot2"}</script>

<script class="next-config" data-name="calendar" type="application/json">""</script>
<title>Plotting Sentinel-5P NetCDF products with R and ggplot2 | Space to Ground</title>
  






  <script async defer data-website-id="" src=""></script>

  <script defer data-domain="" src=""></script>

  <noscript>
    <link rel="stylesheet" href="/css/noscript.css">
  </noscript>
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="use-motion">
  <div class="headband"></div>

  <main class="main">
    <div class="column">
      <header class="header" itemscope itemtype="http://schema.org/WPHeader"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="Toggle navigation bar" role="button">
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
    </div>
  </div>

  <div class="site-meta">

    <a href="/" class="brand" rel="start">
      <i class="logo-line"></i>
      <p class="site-title">Space to Ground</p>
      <i class="logo-line"></i>
    </a>
      <p class="site-subtitle" itemprop="description">Notes from an earth observation engineer's life</p>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger" aria-label="Search" role="button">
    </div>
  </div>
</div>



<nav class="site-nav">
  <ul class="main-menu menu"><li class="menu-item menu-item-home"><a href="/" rel="section"><i class="fa fa-home fa-fw"></i>Home</a></li><li class="menu-item menu-item-about"><a href="/about/" rel="section"><i class="fa fa-user fa-fw"></i>About</a></li><li class="menu-item menu-item-tags"><a href="/tags/" rel="section"><i class="fa fa-tags fa-fw"></i>Tags</a></li><li class="menu-item menu-item-categories"><a href="/categories/" rel="section"><i class="fa fa-th fa-fw"></i>Categories</a></li><li class="menu-item menu-item-archives"><a href="/archives/" rel="section"><i class="fa fa-archive fa-fw"></i>Archives</a></li>
  </ul>
</nav>




</header>
        
  
  <aside class="sidebar">

    <div class="sidebar-inner sidebar-nav-active sidebar-toc-active">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-toc">
          Table of Contents
        </li>
        <li class="sidebar-nav-overview">
          Overview
        </li>
      </ul>

      <div class="sidebar-panel-container">
        <!--noindex-->
        <div class="post-toc-wrap sidebar-panel">
            <div class="post-toc animated"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#Handling-NetCDF4-file-in-R"><span class="nav-number">1.</span> <span class="nav-text">Handling NetCDF4 file in R</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#Preparing-the-data-frame"><span class="nav-number">2.</span> <span class="nav-text">Preparing the data frame</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#Plotting-the-data"><span class="nav-number">3.</span> <span class="nav-text">Plotting the data</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#Conclusion"><span class="nav-number">4.</span> <span class="nav-text">Conclusion</span></a></li></ol></div>
        </div>
        <!--/noindex-->

        <div class="site-overview-wrap sidebar-panel">
          <div class="site-author animated" itemprop="author" itemscope itemtype="http://schema.org/Person">
  <p class="site-author-name" itemprop="name">Stefano Mattia</p>
  <div class="site-description" itemprop="description"></div>
</div>
<div class="site-state-wrap animated">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
        <a href="/archives/">
          <span class="site-state-item-count">8</span>
          <span class="site-state-item-name">posts</span>
        </a>
      </div>
      <div class="site-state-item site-state-categories">
          <a href="/categories/">
        <span class="site-state-item-count">2</span>
        <span class="site-state-item-name">categories</span></a>
      </div>
      <div class="site-state-item site-state-tags">
          <a href="/tags/">
        <span class="site-state-item-count">14</span>
        <span class="site-state-item-name">tags</span></a>
      </div>
  </nav>
</div>
  <div class="links-of-author animated">
      <span class="links-of-author-item">
        <a href="https://github.com/stefanomattia" title="GitHub → https:&#x2F;&#x2F;github.com&#x2F;stefanomattia" rel="noopener" target="_blank"><i class="fab fa-github fa-fw"></i>GitHub</a>
      </span>
  </div>

        </div>
      </div>
    </div>

    
  </aside>


    </div>

    <div class="main-inner post posts-expand">


  


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="en">
    <link itemprop="mainEntityOfPage" href="http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="Stefano Mattia">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Space to Ground">
      <meta itemprop="description" content="">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="Plotting Sentinel-5P NetCDF products with R and ggplot2 | Space to Ground">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          Plotting Sentinel-5P NetCDF products with R and ggplot2
        </h1>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">Posted on</span>

      <time title="Created: 2018-02-14 14:31:33" itemprop="dateCreated datePublished" datetime="2018-02-14T14:31:33+01:00">2018-02-14</time>
    </span>
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar-check"></i>
      </span>
      <span class="post-meta-item-text">Edited on</span>
      <time title="Modified: 2018-03-02 14:33:02" itemprop="dateModified" datetime="2018-03-02T14:33:02+01:00">2018-03-02</time>
    </span>
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-folder"></i>
      </span>
      <span class="post-meta-item-text">In</span>
        <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
          <a href="/categories/Earth-Observation/" itemprop="url" rel="index"><span itemprop="name">Earth Observation</span></a>
        </span>
    </span>

  
  
  <span class="post-meta-item">
    
      <span class="post-meta-item-icon">
        <i class="far fa-comment"></i>
      </span>
      <span class="post-meta-item-text">Disqus: </span>
    
    <a title="disqus" href="/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/#disqus_thread" itemprop="discussionUrl">
      <span class="post-comments-count disqus-comment-count" data-disqus-identifier="2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/" itemprop="commentCount"></span>
    </a>
  </span>
  
  
    <span class="post-meta-item" title="Word count in article">
      <span class="post-meta-item-icon">
        <i class="far fa-file-word"></i>
      </span>
      <span class="post-meta-item-text">Word count in article: </span>
      <span>2.1k</span>
    </span>
    <span class="post-meta-item" title="Reading time">
      <span class="post-meta-item-icon">
        <i class="far fa-clock"></i>
      </span>
      <span class="post-meta-item-text">Reading time &asymp;</span>
      <span>8 mins.</span>
    </span>
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
        <p>I recently started to look into the <a target="_blank" rel="noopener" href="https://www.r-project.org/">R language</a>, as part of my growing interest in statistical learning and data analysis. As a first impression, I felt a bit overwhelmed by the number of differences with Python, the vast amount of oddly named libraries, and the many different ways to address a given problem, as opposed to Python, where there is usually a general consensus about a <em>pythonic</em> way to do things.</p>
<p>Anyway, one of the most effective ways to learn a new programming language is to try using it to solve familiar problems. And that is precisely what I have been doing in the past few days, looking into a fast and efficient way to plot some fresh <a target="_blank" rel="noopener" href="http://www.esa.int/Our_Activities/Observing_the_Earth/Copernicus/Sentinel-5P/Satellite">Sentinel-5P</a> <a target="_blank" rel="noopener" href="http://www.tropomi.eu/data-products/nitrogen-dioxide">NO<sub>2</sub></a> data over a world map.</p>
<p>In this post, we are going to read the contents of several NetCDF4 products and turn them into a single data frame, where each row will contain an observation and the related geodetic coordinates. We are then going to <em>slice</em> the global data frame over a region of interest, and plot the correspondent data over a map with <a target="_blank" rel="noopener" href="http://ggplot2.tidyverse.org/">ggplot2</a>. I am sure there are more clever and elegant ways to approach this task and I will make sure to document them in future posts.</p>
<span id="more"></span>

<h2 id="Handling-NetCDF4-file-in-R"><a href="#Handling-NetCDF4-file-in-R" class="headerlink" title="Handling NetCDF4 file in R"></a>Handling NetCDF4 file in R</h2><p>There seems to be a general agreement in the R community that NetCDF4 files should be handled via the <a target="_blank" rel="noopener" href="https://cran.r-project.org/web/packages/ncdf4/index.html">ncdf4</a> package. I noticed that people are also using the <a target="_blank" rel="noopener" href="https://cran.r-project.org/web/packages/raster/index.html">raster</a> package, which can also read NetCDF4 files, but I still have to look into that.<br>Let’s load the needed libraries.</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">library<span class="punctuation">(</span>ncdf4<span class="punctuation">)</span></span><br><span class="line">library<span class="punctuation">(</span>ggplot2<span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<p>We are now going to load a product into the R environment, just to show how to access its attributes.</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># set path and filename</span></span><br><span class="line">ncpath <span class="operator">&lt;-</span> <span class="string">&quot;/Users/stefano/src/s5p/products/S5P_L2_NO2_KNMI_TEST_v001108_run2/&quot;</span></span><br><span class="line">ncname <span class="operator">&lt;-</span> <span class="string">&quot;S5P_TEST_L2__NO2OMI_20171121T120210_20171121T134257_00555_01_001108_20171216T235943&quot;</span>  </span><br><span class="line">ncfname <span class="operator">&lt;-</span> paste<span class="punctuation">(</span>ncpath<span class="punctuation">,</span> ncname<span class="punctuation">,</span> <span class="string">&quot;.nc&quot;</span><span class="punctuation">,</span> sep<span class="operator">=</span><span class="string">&quot;&quot;</span><span class="punctuation">)</span></span><br><span class="line">nc <span class="operator">&lt;-</span> nc_open<span class="punctuation">(</span>ncfname<span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<p>If we were to print the file information with a <code>print(nc)</code> command, we would get the dump of the entire file structure: too much to be included in this post. Therefore, we will save it to a text file. This nifty piece of code will do the trick:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="punctuation">&#123;</span></span><br><span class="line">  sink<span class="punctuation">(</span>paste0<span class="punctuation">(</span>ncpath<span class="punctuation">,</span> ncname<span class="punctuation">,</span> <span class="string">&quot;.txt&quot;</span><span class="punctuation">)</span><span class="punctuation">)</span></span><br><span class="line">  print<span class="punctuation">(</span>nc<span class="punctuation">)</span></span><br><span class="line">  sink<span class="punctuation">(</span><span class="punctuation">)</span></span><br><span class="line"><span class="punctuation">&#125;</span></span><br></pre></td></tr></table></figure>

<p><code>sink</code> diverts R output to a connection (and must be used again to finish such a diversion). We can then display the generated text file in our shell or open it with any text editor. It is very similar to what would be generated using the <code>ncdump</code> tool.</p>
<p>Next, we could display some summary information about this particular product:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">attributes</span><span class="punctuation">(</span>nc<span class="punctuation">)</span><span class="operator">$</span><span class="built_in">names</span></span><br></pre></td></tr></table></figure>

<pre><code>##  [1] &quot;filename&quot;    &quot;writable&quot;    &quot;id&quot;          &quot;safemode&quot;    &quot;format&quot;     
##  [6] &quot;is_GMT&quot;      &quot;groups&quot;      &quot;fqgn2Rindex&quot; &quot;ndims&quot;       &quot;natts&quot;      
## [11] &quot;dim&quot;         &quot;unlimdimid&quot;  &quot;nvars&quot;       &quot;var&quot;
</code></pre>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">attributes</span><span class="punctuation">(</span>nc<span class="punctuation">)</span><span class="operator">$</span><span class="built_in">names</span></span><br><span class="line">print<span class="punctuation">(</span>paste<span class="punctuation">(</span><span class="string">&quot;The file has&quot;</span><span class="punctuation">,</span> nc<span class="operator">$</span>nvars<span class="punctuation">,</span> <span class="string">&quot;variables,&quot;</span><span class="punctuation">,</span> nc<span class="operator">$</span>ndims<span class="punctuation">,</span> </span><br><span class="line">            <span class="string">&quot;dimensions and&quot;</span><span class="punctuation">,</span> nc<span class="operator">$</span>natts<span class="punctuation">,</span> <span class="string">&quot;NetCDF attributes&quot;</span><span class="punctuation">)</span><span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<pre><code>## [1] &quot;The file has 89 variables, 14 dimensions and 943 NetCDF attributes&quot;
</code></pre>
<p>We can access and display all the available variables through the <code>var</code> dimension:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="built_in">attributes</span><span class="punctuation">(</span>nc<span class="operator">$</span>var<span class="punctuation">)</span><span class="operator">$</span><span class="built_in">names</span></span><br></pre></td></tr></table></figure>

<pre><code>##  [1] &quot;PRODUCT/latitude&quot;                                                   
##  [2] &quot;PRODUCT/longitude&quot;                                                  
##  [3] &quot;PRODUCT/delta_time&quot;                                                 
##  [4] &quot;PRODUCT/time_utc&quot;                                                   
##  [5] &quot;PRODUCT/qa_value&quot;                                                   
##  [6] &quot;PRODUCT/nitrogendioxide_tropospheric_column&quot;                        
##  [7] &quot;PRODUCT/nitrogendioxide_tropospheric_column_precision&quot;              
##  [8] &quot;PRODUCT/averaging_kernel&quot;                                           
##  [9] &quot;PRODUCT/air_mass_factor_troposphere&quot;                                
## [10] &quot;PRODUCT/air_mass_factor_total&quot;                                      
## [11] &quot;PRODUCT/tm5_tropopause_layer_index&quot;                                 
## [12] &quot;PRODUCT/tm5_constant_a&quot;                                             
## [13] &quot;PRODUCT/tm5_constant_b&quot;                                             
## [14] &quot;GEOLOCATIONS/satellite_latitude&quot;                                    
## [15] &quot;GEOLOCATIONS/satellite_longitude&quot;                                   
## [16] &quot;GEOLOCATIONS/satellite_altitude&quot;                                    
## [17] &quot;GEOLOCATIONS/satellite_orbit_phase&quot;                                 
## [18] &quot;GEOLOCATIONS/solar_zenith_angle&quot;                                    
## [19] &quot;GEOLOCATIONS/solar_azimuth_angle&quot;                                   
## [20] &quot;GEOLOCATIONS/viewing_zenith_angle&quot;                                  
## [21] &quot;GEOLOCATIONS/viewing_azimuth_angle&quot;                                 
## [22] &quot;GEOLOCATIONS/latitude_bounds&quot;                                       
## [23] &quot;GEOLOCATIONS/longitude_bounds&quot;                                      
## [24] &quot;GEOLOCATIONS/geolocation_flags&quot;                                     
## [25] &quot;DETAILED_RESULTS/processing_quality_flags&quot;                          
## [26] &quot;DETAILED_RESULTS/number_of_spectral_points_in_retrieval&quot;            
## [27] &quot;DETAILED_RESULTS/number_of_iterations&quot;                              
## [28] &quot;DETAILED_RESULTS/wavelength_calibration_offset&quot;                     
## [29] &quot;DETAILED_RESULTS/wavelength_calibration_offset_precision&quot;           
## [30] &quot;DETAILED_RESULTS/wavelength_calibration_stretch&quot;                    
## [31] &quot;DETAILED_RESULTS/wavelength_calibration_stretch_precision&quot;          
## [32] &quot;DETAILED_RESULTS/wavelength_calibration_chi_square&quot;                 
## [33] &quot;DETAILED_RESULTS/wavelength_calibration_irradiance_offset&quot;          
## [34] &quot;DETAILED_RESULTS/wavelength_calibration_irradiance_offset_precision&quot;
## [35] &quot;DETAILED_RESULTS/wavelength_calibration_irradiance_chi_square&quot;      
## [36] &quot;DETAILED_RESULTS/nitrogendioxide_stratospheric_column&quot;              
## [37] &quot;DETAILED_RESULTS/nitrogendioxide_stratospheric_column_precision&quot;    
## [38] &quot;DETAILED_RESULTS/nitrogendioxide_total_column&quot;                      
## [39] &quot;DETAILED_RESULTS/nitrogendioxide_total_column_precision&quot;            
## [40] &quot;DETAILED_RESULTS/nitrogendioxide_summed_total_column&quot;               
## [41] &quot;DETAILED_RESULTS/nitrogendioxide_summed_total_column_precision&quot;     
## [42] &quot;DETAILED_RESULTS/nitrogendioxide_slant_column_density&quot;              
## [43] &quot;DETAILED_RESULTS/nitrogendioxide_slant_column_density_precision&quot;    
## [44] &quot;DETAILED_RESULTS/ozone_slant_column_density&quot;                        
## [45] &quot;DETAILED_RESULTS/ozone_slant_column_density_precision&quot;              
## [46] &quot;DETAILED_RESULTS/oxygen_oxygen_dimer_slant_column_density&quot;          
## [47] &quot;DETAILED_RESULTS/oxygen_oxygen_dimer_slant_column_density_precision&quot;
## [48] &quot;DETAILED_RESULTS/water_slant_column_density&quot;                        
## [49] &quot;DETAILED_RESULTS/water_slant_column_density_precision&quot;              
## [50] &quot;DETAILED_RESULTS/water_liquid_slant_column_density&quot;                 
## [51] &quot;DETAILED_RESULTS/water_liquid_slant_column_density_precision&quot;       
## [52] &quot;DETAILED_RESULTS/ring_coefficient&quot;                                  
## [53] &quot;DETAILED_RESULTS/ring_coefficient_precision&quot;                        
## [54] &quot;DETAILED_RESULTS/polynomial_coefficients&quot;                           
## [55] &quot;DETAILED_RESULTS/polynomial_coefficients_precision&quot;                 
## [56] &quot;DETAILED_RESULTS/cloud_fraction_crb_nitrogendioxide_window&quot;         
## [57] &quot;DETAILED_RESULTS/cloud_radiance_fraction_nitrogendioxide_window&quot;    
## [58] &quot;DETAILED_RESULTS/chi_square&quot;                                        
## [59] &quot;DETAILED_RESULTS/root_mean_square_error_of_fit&quot;                     
## [60] &quot;DETAILED_RESULTS/air_mass_factor_stratosphere&quot;                      
## [61] &quot;DETAILED_RESULTS/nitrogendioxide_ghost_column&quot;                      
## [62] &quot;INPUT_DATA/surface_altitude&quot;                                        
## [63] &quot;INPUT_DATA/surface_altitude_precision&quot;                              
## [64] &quot;INPUT_DATA/surface_classification&quot;                                  
## [65] &quot;INPUT_DATA/instrument_configuration_identifier&quot;                     
## [66] &quot;INPUT_DATA/instrument_configuration_version&quot;                        
## [67] &quot;INPUT_DATA/scaled_small_pixel_variance&quot;                             
## [68] &quot;INPUT_DATA/surface_pressure&quot;                                        
## [69] &quot;INPUT_DATA/surface_albedo_nitrogendioxide_window&quot;                   
## [70] &quot;INPUT_DATA/surface_albedo&quot;                                          
## [71] &quot;INPUT_DATA/cloud_pressure_crb&quot;                                      
## [72] &quot;INPUT_DATA/cloud_fraction_crb&quot;                                      
## [73] &quot;INPUT_DATA/cloud_albedo_crb&quot;                                        
## [74] &quot;INPUT_DATA/scene_albedo&quot;                                            
## [75] &quot;INPUT_DATA/apparent_scene_pressure&quot;                                 
## [76] &quot;INPUT_DATA/snow_ice_flag&quot;                                           
## [77] &quot;INPUT_DATA/aerosol_index_354_388&quot;                                   
## [78] &quot;QA_STATISTICS/nitrogendioxide_stratospheric_column_histogram_bounds&quot;
## [79] &quot;QA_STATISTICS/nitrogendioxide_stratospheric_column_pdf_bounds&quot;      
## [80] &quot;QA_STATISTICS/nitrogendioxide_tropospheric_column_histogram_bounds&quot; 
## [81] &quot;QA_STATISTICS/nitrogendioxide_tropospheric_column_pdf_bounds&quot;       
## [82] &quot;QA_STATISTICS/nitrogendioxide_total_column_histogram_bounds&quot;        
## [83] &quot;QA_STATISTICS/nitrogendioxide_total_column_pdf_bounds&quot;              
## [84] &quot;QA_STATISTICS/nitrogendioxide_tropospheric_column_histogram&quot;        
## [85] &quot;QA_STATISTICS/nitrogendioxide_stratospheric_column_histogram&quot;       
## [86] &quot;QA_STATISTICS/nitrogendioxide_total_column_histogram&quot;               
## [87] &quot;QA_STATISTICS/nitrogendioxide_tropospheric_column_pdf&quot;              
## [88] &quot;QA_STATISTICS/nitrogendioxide_stratospheric_column_pdf&quot;             
## [89] &quot;QA_STATISTICS/nitrogendioxide_total_column_pdf&quot;
</code></pre>
<p>Quite a few of them!</p>
<p>In this post, we am going to focus our attention on the NO<sub>2</sub> total column variable, whose attributes can be read via the <code>ncatt_get</code> function:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">ncatt_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;DETAILED_RESULTS/nitrogendioxide_total_column&quot;</span><span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<pre><code>## $units
## [1] &quot;mol m-2&quot;
## 
## $proposed_standard_name
## [1] &quot;atmosphere_mole_content_of_nitrogen_dioxide&quot;
## 
## $long_name
## [1] &quot;total vertical column of nitrogen dioxide derived from the total slant column and TM5 profile in stratosphere and troposphere&quot;
## 
## $coordinates
## [1] &quot;longitude latitude&quot;
## 
## $ancillary_variables
## [1] &quot;nitrogendioxide_total_column_precision /PRODUCT/averaging_kernel&quot;
## 
## $multiplication_factor_to_convert_to_molecules_percm2
## [1] 6.02214e+19
## 
## $`_FillValue`
## [1] 9.96921e+36
</code></pre>
<p>We are going to save the multiplication factor to convert to molecules&#x2F;cm<sup>2</sup> and the fill value, which will come in handy later:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">mfactor <span class="operator">=</span> ncatt_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;DETAILED_RESULTS/nitrogendioxide_total_column&quot;</span><span class="punctuation">,</span> </span><br><span class="line">                    <span class="string">&quot;multiplication_factor_to_convert_to_molecules_percm2&quot;</span><span class="punctuation">)</span></span><br><span class="line">fillvalue <span class="operator">=</span> ncatt_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;DETAILED_RESULTS/nitrogendioxide_total_column&quot;</span><span class="punctuation">,</span> </span><br><span class="line">                      <span class="string">&quot;_FillValue&quot;</span><span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<p>The actual data is read with the <code>ncvar_get</code> function. We could, for example, read the NO<sub>2</sub> total column data, along with the latitude and longitude information and store them into separate variables.</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">no2tc <span class="operator">&lt;-</span> ncvar_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;DETAILED_RESULTS/nitrogendioxide_total_column&quot;</span><span class="punctuation">)</span></span><br><span class="line">lat <span class="operator">&lt;-</span> ncvar_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;PRODUCT/latitude&quot;</span><span class="punctuation">)</span></span><br><span class="line">lon <span class="operator">&lt;-</span> ncvar_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;PRODUCT/longitude&quot;</span><span class="punctuation">)</span></span><br><span class="line"><span class="built_in">dim</span><span class="punctuation">(</span>no2tc<span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<pre><code>## [1]  450 3246
</code></pre>
<p>The data structure follows the Sentinel-5P product convention to store measurements into a scanline&#x2F;ground pixel rectangular grid. As shown by the <code>dim</code> function, there are 3246 scanlines in this product, each one containing 450 ground pixels. Each ground pixel has associated coordinates stored in the latitude&#x2F;longitude attributes.<br>We can now close the file:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">nc_close<span class="punctuation">(</span>nc<span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<h2 id="Preparing-the-data-frame"><a href="#Preparing-the-data-frame" class="headerlink" title="Preparing the data frame"></a>Preparing the data frame</h2><p>In principle, we could go ahead and plot this data, but the resulting plot would only include a single pass. If we want global coverage, we need to include an entire 15-orbit data set. To do so, we are going to loop over the list of files in the data set, read the content of the <code>nitrogendioxide_total_column</code> attribute and store it into a data frame, along with the associated coordinates. As an intermediate step, we are going to convert the unit to molecules&#x2F;cm<sup>2</sup> using the conversion factor we saved before. Note that we will be flattening the original two-dimensional data structures into a one-dimensional vector, using the <code>as.vector</code> function. On each i<sub>th</sub> iteration, we are going to concatenate the data frame created from the i<sub>th</sub> file to the existing data frame via the <code>rbind</code> function. As the whole process could take some time—it is a 6.6GB data set—we are going to measure the execution time.</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># declare dataframe</span></span><br><span class="line">no2df <span class="operator">=</span> <span class="literal">NULL</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># get filenames</span></span><br><span class="line">no2files <span class="operator">=</span> list.files<span class="punctuation">(</span>ncpath<span class="punctuation">,</span> patter<span class="operator">=</span><span class="string">&quot;*nc&quot;</span><span class="punctuation">,</span> full.names<span class="operator">=</span><span class="literal">TRUE</span><span class="punctuation">)</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># save start time</span></span><br><span class="line">start.time <span class="operator">&lt;-</span> Sys.time<span class="punctuation">(</span><span class="punctuation">)</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># loop over filenames, open each one and add to dataframe</span></span><br><span class="line"><span class="keyword">for</span> <span class="punctuation">(</span>i <span class="keyword">in</span> <span class="built_in">seq_along</span><span class="punctuation">(</span>no2files<span class="punctuation">)</span><span class="punctuation">)</span> <span class="punctuation">&#123;</span></span><br><span class="line">  nc <span class="operator">&lt;-</span> nc_open<span class="punctuation">(</span>no2files<span class="punctuation">[</span>i<span class="punctuation">]</span><span class="punctuation">)</span></span><br><span class="line">  <span class="comment"># get variables of interest</span></span><br><span class="line">  no2tc <span class="operator">&lt;-</span> ncvar_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;DETAILED_RESULTS/nitrogendioxide_total_column&quot;</span><span class="punctuation">)</span>  </span><br><span class="line">  <span class="comment"># apply multiplication factor for unit conversion</span></span><br><span class="line">  no2tc <span class="operator">&lt;-</span> no2tc<span class="operator">*</span>mfactor<span class="operator">$</span>value</span><br><span class="line">  lat <span class="operator">&lt;-</span> ncvar_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;PRODUCT/latitude&quot;</span><span class="punctuation">)</span></span><br><span class="line">  lon <span class="operator">&lt;-</span> ncvar_get<span class="punctuation">(</span>nc<span class="punctuation">,</span> <span class="string">&quot;PRODUCT/longitude&quot;</span><span class="punctuation">)</span></span><br><span class="line">  <span class="comment"># concatenate the new data to the global data frame</span></span><br><span class="line">  no2df <span class="operator">&lt;-</span> rbind<span class="punctuation">(</span>no2df<span class="punctuation">,</span> data.frame<span class="punctuation">(</span>lat<span class="operator">=</span>as.vector<span class="punctuation">(</span>lat<span class="punctuation">)</span><span class="punctuation">,</span> </span><br><span class="line">                                   lon<span class="operator">=</span>as.vector<span class="punctuation">(</span>lon<span class="punctuation">)</span><span class="punctuation">,</span> </span><br><span class="line">                                   no2tc<span class="operator">=</span>as.vector<span class="punctuation">(</span>no2tc<span class="punctuation">)</span><span class="punctuation">)</span><span class="punctuation">)</span></span><br><span class="line">  <span class="comment"># close file</span></span><br><span class="line">  nc_close<span class="punctuation">(</span>nc<span class="punctuation">)</span></span><br><span class="line"><span class="punctuation">&#125;</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># measure elapsed time</span></span><br><span class="line">stop.time <span class="operator">&lt;-</span> Sys.time<span class="punctuation">(</span><span class="punctuation">)</span></span><br><span class="line">time.taken <span class="operator">&lt;-</span> stop.time <span class="operator">-</span> start.time</span><br><span class="line"></span><br><span class="line">print<span class="punctuation">(</span>paste<span class="punctuation">(</span><span class="built_in">dim</span><span class="punctuation">(</span>no2df<span class="punctuation">)</span><span class="punctuation">[</span><span class="number">1</span><span class="punctuation">]</span><span class="punctuation">,</span> <span class="string">&quot;observations read from&quot;</span><span class="punctuation">,</span> <span class="built_in">length</span><span class="punctuation">(</span>no2files<span class="punctuation">)</span><span class="punctuation">,</span> </span><br><span class="line">            <span class="string">&quot;files in&quot;</span><span class="punctuation">,</span> time.taken<span class="punctuation">,</span> <span class="string">&quot;seconds&quot;</span><span class="punctuation">)</span><span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<pre><code>## [1] &quot;30527550 observations read from 21 files in 33.7685630321503 seconds&quot;
</code></pre>
<p>That’s a big data set! Let’s have a look at it:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">head<span class="punctuation">(</span>no2df<span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<pre><code>##         lat       lon no2tc
## 1 -58.18863 -51.95583    NA
## 2 -58.20359 -52.11977    NA
## 3 -58.21814 -52.28154    NA
## 4 -58.23227 -52.44122    NA
## 5 -58.24602 -52.59883    NA
## 6 -58.25938 -52.75446    NA
</code></pre>
<p>As expected, each row contains an NO<sub>2</sub> measurement and the associated coordinates of the center pixel.</p>
<h2 id="Plotting-the-data"><a href="#Plotting-the-data" class="headerlink" title="Plotting the data"></a>Plotting the data</h2><p>To display regional plot, we’d better subset the data frame first, that is, we are going to reduce the number of pixels (or data frame rows) handed over to the plot function, by means of coordinate boundaries. We are also going to filter out all entries containing the fill value. As we don’t want to duplicate code every time we make a new plot, we are going to define a function that accepts boundary coordinates and plot the correspondent region on a map.</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br></pre></td><td class="code"><pre><span class="line">PlotRegion <span class="operator">&lt;-</span> <span class="keyword">function</span><span class="punctuation">(</span>df<span class="punctuation">,</span> latlon<span class="punctuation">,</span> title<span class="punctuation">)</span> <span class="punctuation">&#123;</span></span><br><span class="line">  <span class="comment"># Plot the given dataset over a geographic region.</span></span><br><span class="line">  <span class="comment">#</span></span><br><span class="line">  <span class="comment"># Args:</span></span><br><span class="line">  <span class="comment">#   df: The dataset, should include the no2tc, lat, lon columns</span></span><br><span class="line">  <span class="comment">#   latlon: A vector of four values identifying the botton-left and top-right corners </span></span><br><span class="line">  <span class="comment">#           c(latmin, latmax, lonmin, lonmax)</span></span><br><span class="line">  <span class="comment">#   title: The plot title</span></span><br><span class="line">  </span><br><span class="line">  <span class="comment"># subset the data frame first</span></span><br><span class="line">  df_sub <span class="operator">&lt;-</span> subset<span class="punctuation">(</span>df<span class="punctuation">,</span> no2tc<span class="operator">!=</span>fillvalue <span class="operator">&amp;</span> lat<span class="operator">&gt;</span>latlon<span class="punctuation">[</span><span class="number">1</span><span class="punctuation">]</span> <span class="operator">&amp;</span> lat<span class="operator">&lt;</span>latlon<span class="punctuation">[</span><span class="number">2</span><span class="punctuation">]</span> <span class="operator">&amp;</span> lon<span class="operator">&gt;</span>latlon<span class="punctuation">[</span><span class="number">3</span><span class="punctuation">]</span> <span class="operator">&amp;</span> lon<span class="operator">&lt;</span>latlon<span class="punctuation">[</span><span class="number">4</span><span class="punctuation">]</span><span class="punctuation">)</span></span><br><span class="line">  subtitle <span class="operator">=</span> paste<span class="punctuation">(</span><span class="string">&quot;Data min =&quot;</span><span class="punctuation">,</span> formatC<span class="punctuation">(</span><span class="built_in">min</span><span class="punctuation">(</span>df_sub<span class="operator">$</span>no2tc<span class="punctuation">,</span> na.rm<span class="operator">=</span><span class="built_in">T</span><span class="punctuation">)</span><span class="punctuation">,</span> format<span class="operator">=</span><span class="string">&quot;e&quot;</span><span class="punctuation">,</span> digits<span class="operator">=</span><span class="number">2</span><span class="punctuation">)</span><span class="punctuation">,</span> </span><br><span class="line">                   <span class="string">&quot;max =&quot;</span><span class="punctuation">,</span> formatC<span class="punctuation">(</span><span class="built_in">max</span><span class="punctuation">(</span>df_sub<span class="operator">$</span>no2tc<span class="punctuation">,</span> na.rm<span class="operator">=</span><span class="built_in">T</span><span class="punctuation">)</span><span class="punctuation">,</span> format<span class="operator">=</span><span class="string">&quot;e&quot;</span><span class="punctuation">,</span> digits<span class="operator">=</span><span class="number">2</span><span class="punctuation">)</span><span class="punctuation">)</span></span><br><span class="line"></span><br><span class="line">  ggplot<span class="punctuation">(</span>df_sub<span class="punctuation">,</span> aes<span class="punctuation">(</span>y<span class="operator">=</span>lat<span class="punctuation">,</span> x<span class="operator">=</span>lon<span class="punctuation">,</span> fill<span class="operator">=</span>no2tc<span class="punctuation">)</span><span class="punctuation">)</span> <span class="operator">+</span> </span><br><span class="line">    geom_tile<span class="punctuation">(</span>width<span class="operator">=</span><span class="number">1</span><span class="punctuation">,</span> height<span class="operator">=</span><span class="number">1</span><span class="punctuation">)</span> <span class="operator">+</span></span><br><span class="line">    borders<span class="punctuation">(</span><span class="string">&#x27;world&#x27;</span><span class="punctuation">,</span> xlim<span class="operator">=</span><span class="built_in">range</span><span class="punctuation">(</span>df_sub<span class="operator">$</span>lon<span class="punctuation">)</span><span class="punctuation">,</span> ylim<span class="operator">=</span><span class="built_in">range</span><span class="punctuation">(</span>df_sub<span class="operator">$</span>lat<span class="punctuation">)</span><span class="punctuation">,</span> </span><br><span class="line">            colour<span class="operator">=</span><span class="string">&#x27;gray90&#x27;</span><span class="punctuation">,</span> size<span class="operator">=</span><span class="number">.2</span><span class="punctuation">)</span> <span class="operator">+</span> </span><br><span class="line">    theme_light<span class="punctuation">(</span><span class="punctuation">)</span> <span class="operator">+</span> </span><br><span class="line">    theme<span class="punctuation">(</span>panel.ontop<span class="operator">=</span><span class="literal">TRUE</span><span class="punctuation">,</span> panel.background<span class="operator">=</span>element_blank<span class="punctuation">(</span><span class="punctuation">)</span><span class="punctuation">)</span> <span class="operator">+</span></span><br><span class="line">    scale_fill_distiller<span class="punctuation">(</span>palette<span class="operator">=</span><span class="string">&#x27;Spectral&#x27;</span><span class="punctuation">,</span> </span><br><span class="line">                         limits<span class="operator">=</span><span class="built_in">c</span><span class="punctuation">(</span>quantile<span class="punctuation">(</span>df_sub<span class="punctuation">,</span> <span class="number">.7</span><span class="punctuation">,</span> na.rm<span class="operator">=</span><span class="built_in">T</span><span class="punctuation">)</span><span class="punctuation">,</span> </span><br><span class="line">                                  quantile<span class="punctuation">(</span>df_sub<span class="punctuation">,</span> <span class="number">.999</span><span class="punctuation">,</span> na.rm<span class="operator">=</span><span class="built_in">T</span><span class="punctuation">)</span><span class="punctuation">)</span><span class="punctuation">)</span> <span class="operator">+</span></span><br><span class="line">    coord_quickmap<span class="punctuation">(</span>xlim<span class="operator">=</span><span class="built_in">c</span><span class="punctuation">(</span>latlon<span class="punctuation">[</span><span class="number">3</span><span class="punctuation">]</span><span class="punctuation">,</span> latlon<span class="punctuation">[</span><span class="number">4</span><span class="punctuation">]</span><span class="punctuation">)</span><span class="punctuation">,</span> ylim<span class="operator">=</span><span class="built_in">c</span><span class="punctuation">(</span>latlon<span class="punctuation">[</span><span class="number">1</span><span class="punctuation">]</span><span class="punctuation">,</span> latlon<span class="punctuation">[</span><span class="number">2</span><span class="punctuation">]</span><span class="punctuation">)</span><span class="punctuation">)</span> <span class="operator">+</span></span><br><span class="line">    labs<span class="punctuation">(</span>title<span class="operator">=</span>title<span class="punctuation">,</span> subtitle<span class="operator">=</span>subtitle<span class="punctuation">,</span> </span><br><span class="line">         x<span class="operator">=</span><span class="string">&quot;Longitude&quot;</span><span class="punctuation">,</span> y<span class="operator">=</span><span class="string">&quot;Latitude&quot;</span><span class="punctuation">,</span> </span><br><span class="line">         fill<span class="operator">=</span><span class="built_in">expression</span><span class="punctuation">(</span>molecules<span class="operator">~</span>cm<span class="operator">^</span><span class="operator">-</span><span class="number">2</span><span class="punctuation">)</span><span class="punctuation">)</span></span><br><span class="line"><span class="punctuation">&#125;</span></span><br></pre></td></tr></table></figure>

<p>There is a lot going on when calling the <code>ggplot</code> function, and the syntax might look a bit puzzling at first. Basically, we first need to define the base plot specifying the data to use and the aesthetics, and after that we can add more layers and themes to it. I played a bit with the limits controlling the color scale in the <code>scale_fill_distiller</code> function in order to convey more information in the plot, which would otherwise look too <em>flat</em>, because of the outliers.</p>
<p>Let’s see how it looks like. Let’s define some coordinate boundaries over Europe:</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">eu.coords <span class="operator">=</span> <span class="built_in">c</span><span class="punctuation">(</span><span class="number">34</span><span class="punctuation">,</span> <span class="number">60</span><span class="punctuation">,</span> <span class="operator">-</span><span class="number">15</span><span class="punctuation">,</span> <span class="number">35</span><span class="punctuation">)</span></span><br><span class="line">PlotRegion<span class="punctuation">(</span>no2df<span class="punctuation">,</span> eu.coords<span class="punctuation">,</span> <span class="built_in">expression</span><span class="punctuation">(</span>NO<span class="punctuation">[</span><span class="number">2</span><span class="punctuation">]</span><span class="operator">~</span>total<span class="operator">~</span>vertical<span class="operator">~</span>column<span class="operator">~</span>over<span class="operator">~</span>Europe<span class="punctuation">)</span><span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<img src="/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/unnamed-chunk-13-1.png" class="">

<p>That looks amazing! Well, not so much for our lungs, but still…<br>Pollution on the Po Valley in Italy is clearly visible, as well as bright spots on Madrid, Algiers, and Prague. The whole area over the Netherlands, Denmark, and Germany seems to be wrapped in a tick layer of NO<sub>2</sub>. Some artifacts are noticeable on the east side of Great Britain, that’s probably due to overlapping orbits, as our original data set contained more than fifteen orbits.<br>A clever approach in this case would have been to apply some binning and averaging when building the data frame, but that is possibly a topic for a future post.</p>
<p>Curious about how North America is faring with their NO<sub>2</sub> concentration? Let’s see!</p>
<figure class="highlight r"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">us.coords <span class="operator">=</span> <span class="built_in">c</span><span class="punctuation">(</span><span class="number">15</span><span class="punctuation">,</span> <span class="number">64</span><span class="punctuation">,</span> <span class="operator">-</span><span class="number">135</span><span class="punctuation">,</span> <span class="operator">-</span><span class="number">40</span><span class="punctuation">)</span></span><br><span class="line">PlotRegion<span class="punctuation">(</span>no2df<span class="punctuation">,</span> us.coords<span class="punctuation">,</span> <span class="built_in">expression</span><span class="punctuation">(</span>NO<span class="punctuation">[</span><span class="number">2</span><span class="punctuation">]</span><span class="operator">~</span>total<span class="operator">~</span>vertical<span class="operator">~</span>column<span class="operator">~</span>over<span class="operator">~</span>USA<span class="punctuation">)</span><span class="punctuation">)</span></span><br></pre></td></tr></table></figure>

<img src="/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/unnamed-chunk-14-1.png" class="">

<p>Here we can clearly see the different passes, each of them 3000km wide and acquired 100 minutes apart from each other. We can easily spot San Francisco and the Los Angeles&#x2F;San Diego area on the west coast, Mexico City in the south, and Chicago in the mid-west. The whole north-east coast seems to be the area most affected by pollution.</p>
<h2 id="Conclusion"><a href="#Conclusion" class="headerlink" title="Conclusion"></a>Conclusion</h2><p>In this post, we went through a few key concepts on dealing with NetCDF data in R: handling NetCDF files, extracting data from multiple files and building data frames, subsetting data frames and plotting the results. I don’t even feel like I have scratched the surface of what can be done with R and <code>ggplot2</code>, but hopefully this post gives an idea on how easy it is to handle and display atmosphere chemistry data in R. In the future, I’d like to look into <a target="_blank" rel="noopener" href="https://blog.dominodatalab.com/geographic-visualization-with-rs-ggmaps/">visualizing heatmaps</a> with the <a target="_blank" rel="noopener" href="https://github.com/dkahle/ggmap"><code>ggmap</code></a> package.</p>
<p>I hope you enjoyed this post, feel free to comment if you have questions or remarks.</p>
<p>References:</p>
<ol>
<li><a target="_blank" rel="noopener" href="http://geog.uoregon.edu/bartlein/courses/geog490/week04-netCDF.html">NetCDF in R</a></li>
<li><a target="_blank" rel="noopener" href="https://cran.r-project.org/web/packages/futureheatwaves/vignettes/starting_from_netcdf.html">Starting from netCDF files</a></li>
<li><a target="_blank" rel="noopener" href="https://stackoverflow.com/questions/43612903/how-to-properly-plot-projected-gridded-data-in-ggplot2">How to properly plot projected gridded data in ggplot2?</a></li>
</ol>
<p><em>This post was written entirely in R markdown. You can download it on my <a target="_blank" rel="noopener" href="https://github.com/stefanomattia/r-markdown/tree/master/earth-observation">GitHub repository</a>.</em></p>
<p><em>Disclaimer: the data shown in this post should not be considered representative of TROPOMI operational capabilities as the instrument is still undergoing its validation phase.</em></p>

    </div>

    
    
    

    <footer class="post-footer">
          <div class="post-tags">
              <a href="/tags/rstats/" rel="tag"># rstats</a>
              <a href="/tags/ggplot2/" rel="tag"># ggplot2</a>
          </div>

        

          <div class="post-nav">
            <div class="post-nav-item">
                <a href="/2017/12/12/The-quest-to-find-the-closest-ground-pixel/" rel="prev" title="The quest to find the closest ground pixel">
                  <i class="fa fa-chevron-left"></i> The quest to find the closest ground pixel
                </a>
            </div>
            <div class="post-nav-item">
                <a href="/2018/03/27/Mount-Sinabung-eruption-as-seen-by-Sentinel-5P/" rel="next" title="Mount Sinabung eruption as seen by Sentinel-5P">
                  Mount Sinabung eruption as seen by Sentinel-5P <i class="fa fa-chevron-right"></i>
                </a>
            </div>
          </div>
    </footer>
  </article>
</div>






    
  <div class="comments" id="disqus_thread">
    <noscript>Please enable JavaScript to view the comments powered by Disqus.</noscript>
  </div>
  
</div>
  </main>

  <footer class="footer">
    <div class="footer-inner">


<div class="copyright">
  &copy; 
  <span itemprop="copyrightYear">2022</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Stefano Mattia</span>
</div>
<div class="wordcount">
  <span class="post-meta-item">
    <span class="post-meta-item-icon">
      <i class="fa fa-chart-line"></i>
    </span>
    <span title="Word count total">28k</span>
  </span>
  <span class="post-meta-item">
    <span class="post-meta-item-icon">
      <i class="fa fa-coffee"></i>
    </span>
    <span title="Reading time total">1:43</span>
  </span>
</div>
  <div class="powered-by">Powered by <a href="https://hexo.io/" rel="noopener" target="_blank">Hexo</a> & <a href="https://theme-next.js.org/muse/" rel="noopener" target="_blank">NexT.Muse</a>
  </div>

    </div>
  </footer>

  
  <div class="toggle sidebar-toggle" role="button">
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
  </div>
  <div class="sidebar-dimmer"></div>
  <div class="back-to-top" role="button" aria-label="Back to top">
    <i class="fa fa-arrow-up fa-lg"></i>
    <span>0%</span>
  </div>

<noscript>
  <div class="noscript-warning">Theme NexT works best with JavaScript enabled</div>
</noscript>


  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js" integrity="sha256-XL2inqUJaslATFnHdJOi9GfQ60on8Wx1C2H8DYiN1xY=" crossorigin="anonymous"></script>
<script src="/js/comments.js"></script><script src="/js/utils.js"></script><script src="/js/motion.js"></script><script src="/js/schemes/muse.js"></script><script src="/js/next-boot.js"></script>

  




  




  

  <script class="next-config" data-name="enableMath" type="application/json">false</script><script class="next-config" data-name="mathjax" type="application/json">{"enable":true,"tags":"none","js":{"url":"https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js","integrity":"sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="}}</script>
<script src="/js/third-party/math/mathjax.js"></script>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/quicklink/2.3.0/quicklink.umd.js" integrity="sha256-yvJQOINiH9fWemHn0vCA5lsHWJaHs6/ZmO+1Ft04SvM=" crossorigin="anonymous"></script>
  <script class="next-config" data-name="quicklink" type="application/json">{"enable":true,"home":true,"archive":true,"delay":true,"timeout":3000,"priority":true,"url":"http://stefanomattia.github.io/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/"}</script>
  <script src="/js/third-party/quicklink.js"></script>
<script class="next-config" data-name="disqus" type="application/json">{"enable":true,"shortname":"stefanomattia","count":true,"i18n":{"disqus":"disqus"}}</script>
<script src="/js/third-party/comments/disqus.js"></script>

</body>
</html>
